/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Figtree', 'system-ui', 'sans-serif'],
        serif: ['Lora', 'Georgia', 'serif'],
      },
      colors: {
        bg:           '#E8E5DF',
        surface:      '#E8E5DF',
        accent:       '#E0672F',
        'accent-deep':'#D85A30',
        sage:         '#5C8A6B',
        terracotta:   '#C4664A',
        clay:         '#6B8CA8',
        divider:      '#D0CCC4',
        'segment-bg': '#DEDAD4',
        'shadow-light':'#FDFBF6',
        'shadow-dark': '#C7C3BA',
        'text-primary':   '#2A2A2E',
        'text-secondary': '#8A8A8E',
        cal: {
          1:  '#4A90D9',
          2:  '#9B59B6',
          3:  '#E74C3C',
          4:  '#1ABC9C',
          5:  '#F39C12',
          6:  '#2ECC71',
          7:  '#E91E63',
          8:  '#00BCD4',
          9:  '#FF5722',
          10: '#795548',
        },
      },
      borderRadius: {
        card:    '24px',
        button:  '18px',
        banner:  '24px',
        pill:    '9999px',
        seg:     '16px',
        'seg-tab':'12px',
        small:   '16px',
        icon:    '9999px',
      },
      fontSize: {
        'h1':       ['30px', { lineHeight: '1.2', fontWeight: '600' }],
        'subhead':  ['17px', { lineHeight: '1.4', fontWeight: '600' }],
        'amount-xl':['34px', { lineHeight: '1.1', fontWeight: '700' }],
        'amount-lg':['26px', { lineHeight: '1.1', fontWeight: '700' }],
        'amount-md':['18px', { lineHeight: '1.2', fontWeight: '700' }],
        'label':    ['11px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '0.5px' }],
        'section':  ['11px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '1px' }],
      },
    },
  },
  plugins: [],
}
